name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Add $GOPATH/bin to $PATH
      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Cross build
      run: make cross
    - name: Create Release
      run: make upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
